### ISSUE TITLE
Add Better PDF keyphrase extraction modules

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/hexa_lite#1]
The Python based PDF modules are much better than the current version of the project. Please update text extraction modules of the project.

**Comment by AmanPriyanshu** [comment]
I would like to try this out. I have worked on a project on similar lines for pdf-content extraction. I can deliver that in a modular fashion.

**Comment by onosyoono** [comment]
If you have such a code, you can definitely take up this issue, in the mean time please link the resources you will be using.

**Comment by AmanPriyanshu** [comment]
Yup, I'll be using [PyPDF2](https://mstamy2.github.io/PyPDF2/) for this implementation, if that's ok?

**Comment by onosyoono** [comment]
Ok nice work, I would expect you to provide the version of the module you are using at present as well for consistency.
